# Generated by Django 4.1 on 2022-08-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=128)),
            ],
        ),
    ]
