# Generated by Django 4.1 on 2022-09-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddisplay', '0003_search_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
