# Generated by Django 4.1 on 2022-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddisplay', '0004_card_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(max_length=8),
        ),
    ]
